### PR TITLE
Create, edit and delete posts, user feed with latest and trending filter added

### PR DESCRIPTION
**Pull request by xsaurabhsuthar**
* It also has a feature to handle any image/gif files. 
image
image
image

* Right side is kept intentionally red for the development purpose only.

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
code is modular and naming convention is also good .

**Review by shraddha-amber — APPROVED** [review]
Learned a new method to check window width
Liked how you wrote such modular code 

The preview doesn't work tho, it is stuck at a blank screen with landing page text

**Comment by xsaurabhsuthar** [comment]
You can use this to sign up https://quiet-media-git-posts-launchpad5682.vercel.app/signup.

**Comment by xsaurabhsuthar** [comment]
Thanks @tanishk15sharma and @shraddha-1402

**Pull request merged**
